resolved issue-15
designsystemau/gold-design-system-site pull request #19
Opened 2022-09-01 09:38 UTC by Zubiii

2022-09-01 10:38 UTC, dominikwilkowski requested changes
Thanks for the PR.
Can you give some notes on what the issues was and how you fixed it?
I left a couple comments for cleaning this up

2022-09-01 10:38 UTC, dominikwilkowski commented on src/js/a11y/020-tabbing.js
> + function Tab() {
Can we clean this up?
```suggestion
function Tab() {
```

2022-09-01 10:38 UTC, dominikwilkowski commented on src/js/a11y/020-tabbing.js
> +	var loop = 0;
whitespace issues. Perhaps you should use prettier again?
```suggestion
	var loop = 0;
```

2022-09-01 10:38 UTC, dominikwilkowski commented on src/js/a11y/020-tabbing.js
> +	console.log("Tab is calling")
We should not have any console logs in the code
```suggestion
```

2022-09-01 10:38 UTC, dominikwilkowski commented on src/js/a11y/020-tabbing.js
> -
Why was this removed?

2022-09-01 10:38 UTC, dominikwilkowski commented on src/js/a11y/020-tabbing.js
> +		else{
prettier
```suggestion
		else {
```

2022-09-01 10:38 UTC, dominikwilkowski commented on src/js/a11y/020-tabbing.js
> -	$this.focus();
Why was this removed?

2022-09-01 10:38 UTC, dominikwilkowski commented
This PR is to fix #15

2022-09-01 12:59 UTC, Zubiii commented
let me remove white spaces, and update PR.

2022-09-01 13:03 UTC, Zubiii commented on src/js/a11y/020-tabbing.js
> -
I guess this was removed by mistake. Sorry for that. Let me update the PR.

2022-09-01 19:46 UTC, dominikwilkowski requested changes
Very much appreciate your efforts here @Zubiii 
It would really help if you could outline what the issue was and how you fixed it.
I don't have time unfortunately to look into this more deeply.

2022-09-01 19:46 UTC, dominikwilkowski commented on src/js/a11y/020-tabbing.js
> -	$this.focus();
This function get's passed in `document.querySelector( '.js-tabbing-switch' )` on line 41 which is the same as your new line 42. I don't understand why moving it outside this function would fix anything?

2022-09-01 19:46 UTC, dominikwilkowski commented on src/js/a11y/020-tabbing.js
> + AddEvent( document.querySelector( '.tabbing-frame' ), 'keydown', function( event, $this ) {
Can you click on the button below here and accept the change?
```suggestion
AddEvent( document.querySelector( '.tabbing-frame' ), 'keydown', function( event, $this ) {
```

2022-09-01 19:46 UTC, dominikwilkowski commented on src/js/a11y/020-tabbing.js
> +		}else{
```suggestion
		} else {
```

2022-09-01 19:56 UTC, Zubiii commented on src/js/a11y/020-tabbing.js
> +		}else{
**ISSUE:**
`$this.focus();` is basically is forcely focused on the current element. 
**RESOLVE:**
So we removed `$this.focus()` and use `queryselector() ` so that "tab" event can be easily triggered after auto tabbing loop.

2022-09-01 22:46 UTC, dominikwilkowski commented
@Zubiii since `$this` in all instances of calling `StopTab()` is using `queryselector` I don't see how this code is different from the code before?

Perhaps the issue is the order at which `focus` is called?

2022-09-01 23:54 UTC, Zubiii commented
hmm maybe, let me also check the order.

2022-09-02 00:43 UTC, Zubiii commented
Order has not seemed any effect on this issue. I just make a short video and send it to you on the slack community channel, where I probably described the issue and how I solved that. Thanks

2022-09-02 02:32 UTC, dominikwilkowski commented
I have submitted a [PR](https://github.com/Zubiii/gold-design-system-site/pull/1) to your branch. This should fix the issue and once it's merged on your end we can merge this PR

2022-09-02 08:16 UTC, dominikwilkowski approved these changes

2022-09-02 08:19 UTC, merged